apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'python'
        static_configs:
          - targets: ['app.app:8080']
      - job_name: 'traefik'
        static_configs:
          - targets: ['traefik-web-ui.traefik:8082']
