kind: Service
apiVersion: v1
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 8080
    targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
  - name: grafana
    port: 8080
    targetPort: 3000
  selector:
    app: grafana
