---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: prom
    port: 8080
    targetPort: 8080
