kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: web
    port: 80
    targetPort: 8080
  - name: prom
    port: 34610
    targetPort: 34610
  - name: graf
    port: 34620
    targetPort: 34620
