---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: app.minikube
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: app
          servicePort: 80
